homeassistant:
  # Overwrite entity UI fields
  customize: !include_dir_merge_named customizations/entities

  # Customize entities matching a pattern
  customize_glob: !include_dir_merge_named customizations/glob

  # Load integrations from separate files
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

automation: !include automations.yaml
group: !include groups.yaml
input_number: !include input_number.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
